apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - openshift-local-storage-operator-subscription.yaml
  - openshift-local-storage-operator-operatorgroup.yaml
