apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: local-storage-subscription
  namespace: openshift-local-storage
spec:
  name: local-storage-operator
  channel: patch-me-see-overlays-dir
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
