apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: local-parts
  namespace: openshift-local-storage
spec:
  deviceInclusionSpec:
    deviceTypes:
      - part
    minSize: 1Gi
  storageClassName: local-fs
  volumeMode: Filesystem
  fsType: xfs
